### ISSUE TITLE
[Code Generation] Need details about external types referenced in typesUsed array

### ISSUE THREAD

**Issue by felipecsl** [apollostack/apollo-android#13]
From Slack discussion:

felipecsl [12:21 PM]  
@martijnwalraven I was looking at the `HeroAppearsIn` query and the generated IR references the `Episode` type in the `typesUsed` array, however its definition can’t be found anywhere in the data. Also I checked the Swift code generated for that query and noticed that it does include a `public enum Episode`. Sounds like we’re gonna have to add the definition of any external types to the IR so we can generate code based solely on the IR. It sounds like the Swift generator is retrieving that data from somewhere else

**Comment by martijnwalraven** [comment]
I just published version 0.9.5 of apollo-codegen, which now [includes type information as part of `typesUsed`](https://github.com/apollostack/apollo-codegen/commit/a90cf59a4afb4f4ec372e568c3e40f63a1d5fcd1). Types can be either `EnumType` or `InputObjectType`.

**Comment by sav007** [comment]
Issue to add support of enum types has been created: #22

**Comment by felipecsl** [comment]
This has been taken care of already. Will create a separate issue for handling `InputObjectType`
