### ISSUE TITLE
Generated classes are created under generatedIR package

### ISSUE THREAD

**Issue by felipecsl** [apollostack/apollo-android#69]
The gradle plugin doesn't seem to be respecting the original package name of each graphql file and just adding them all into the `generatedIR` package (eg.: `build/generated/source/apollo/generatedIR/DroidDetails.java`)

The generated package name should match the original file path.

**Comment by martijnwalraven** [comment]
If we go down this path, note that generated operations will also have to be aware of the package names of the referenced fragments.

**Comment by marwanad** [comment]
I'll take a look at that one.
